image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https 
      dotnet restore
      dotnet build
  - name: Run
    command: dotnet test


vscode:
  extensions:
    - muhammad-sammy.csharp
    - formulahendry.dotnet-test-explorer
    - jsw.csharpextensions

ports:
  - port: 5000
    onOpen: open-preview